=== international-orienteering-federation/datastandard-v1/v0.1.3/iofControlInfo.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT ControlInfo (Description,EUnit*, PunchPattern*)>
<!ATTLIST ControlInfo
 Name CDATA #IMPLIED
 X_Coordinate CDATA #IMPLIED
 Y_Coordinate CDATA #IMPLIED 
 X_TextOffset CDATA #IMPLIED
 Y_TextOffset CDATA #IMPLIED
 FreeText     CDATA #IMPLIED
 ModifyDate   CDATA #IMPLIED
>

<!ELEMENT Description (Box*)>
<!ELEMENT Box (Symbol | Text)?>

<!ATTLIST Box
  column  (A|B|C|D|E|F|G|H)  #REQUIRED
  hasDiagonal (Y|N) "N"
>

<!ELEMENT Symbol EMPTY>
<!ATTLIST Symbol 
  Order    CDATA #REQUIRED
  Id       CDATA #REQUIRED
>

<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text
  Order    CDATA #REQUIRED
>
 
<!ATTLIST Description
  ModifyDate CDATA #IMPLIED
>

<!ELEMENT EUnit EMPTY> 
<!ATTLIST EUnit
  UnitCode   CDATA #REQUIRED
  Type       CDATA #REQUIRED
  ModifyDate CDATA #IMPLIED
>

<!ELEMENT PunchPattern (#PCDATA)>

=== international-orienteering-federation/datastandard-v1/v0.1.3/examples/iofControlInfo.xml
<?xml version="1.0"?>
<!DOCTYPE ControlInfo SYSTEM "iofControlInfo.dtd">

<ControlInfo Name="Sponsor-IOF" X_Coordinate="100" Y_Coordinate="234" X_TextOffset="5" Y_TextOffset="6" FreeText="Place any text here" ModifyDate="2000.05.23">
   <Description>
     <Box column="A">
       <Symbol Order="1" Id="245"/>
     </Box>
     <Box column="C">
       <Symbol Order="1" Id="247"/>
     </Box>
     <Box column="D">
       <Text Order="1">2x4</Text>
     </Box>
     <Box column="F">
       <Symbol Order="1" Id="245"/>
     </Box>
   </Description>
   <EUnit UnitCode="31" Type="SI"/>
</ControlInfo>
